name: Docker Image CI

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build and Push Docker image
              uses: docker/build-push-action@v1.1.0
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: forrestab/freyr
                tag_with_ref: true
                push: ${{ startsWith(github.ref, 'refs/tags/') }}
